package com.task_service.task_service.security;

public enum ActionType {
    DELETE_MESSAGE, EDIT_MESSAGE, DELETE_MESSAGE_FORALL,
    CREATE_TASK, DELETE_TASK, EDIT_TASK, VIEW_TASK,
    CREATE_CHATROOM, DELETE_CHATROOM, EDIT_CHATROOM_INFO, ADD_MEMBER, REMOVE_MEMBER, PROMOTE_MEMBER, DEMOTE_MEMBER, CHANGE_OWNER,
    CREATE_EMPLOYEE, DELETE_EMPLOYEE, EDIT_EMPLOYEE, VIEW_EMPLOYEE,
    CREATE_EMPLOYMENT, DELETE_EMPLOYMENT, EDIT_EMPLOYMENT, VIEW_EMPLOYMENT, PROMOTE_EMPLOYMENT, DEMOTE_EMPLOYMENT, CHANGE_BOSS,
    CREATE_ORGANIZATION, DELETE_ORGANIZATION, EDIT_ORGANIZATION, VIEW_ORGANIZATION, GET_ORGANIZATION_DETAILS,
    CREATE_UNIT, DELETE_UNIT, EDIT_UNIT, VIEW_UNIT, VIEW_ALL_UNITS,
    EDIT_ACCOUNT, VIEW_ACCOUNT,
    GET_ACCOUNT_UNITS, DELETE_ACCOUNT, GET_ACCOUNT_ORGANIZATION
}
